# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: "2"

networks:
  ifinca:

services:
  tlsca-orderer-ifinca:
    image: hyperledger/fabric-ca:1.4.9
    restart: always
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CSR_CN=tlsca-orderer-ifinca
      - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
      - FABRIC_CA_SERVER_CA_NAME=tlsca-orderer-ifinca
      - FABRIC_CA_SERVER_PORT=6054
    ports:
      - "6054:6054"
    command: sh -c 'fabric-ca-server start -d -b admin:nqxudiHv -p 6054'
    volumes:
      - ./data/tlsca-orderer-ifinca:/etc/hyperledger/fabric-ca-server
    container_name: tlsca-orderer-ifinca
    networks:
      - ifinca
